<package format="3">
  <name>locomanip_controller</name>
  <version>0.1.0</version>
  <description>
    Humanoid loco-manipulation controller
  </description>
  <maintainer email="m-murooka@aist.go.jp">Masaki Murooka</maintainer>
  <license>BSD</license>

  <url>http://ros.org/wiki/locomanip_controller</url>
  <author>Masaki Murooka</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>baseline_walking_controller</depend>
  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>

  <build_depend>eigen</build_depend>

  <exec_depend>rviz2</exec_depend>
  <exec_depend>cnoid_ros2_utils</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
